all:
	echo "Building g1000-simulator"
	@echo "No specific build steps defined yet."

run:
	echo "Running g1000-simulator"
	@echo "No specific run steps defined yet."

test:
	echo "Running tests for g1000-simulator"
	@echo "No specific test steps defined yet."

.PHONY: all run test
