packages:
  - "packages/*"
  - "apps/*"
  - "apps/aviation-accident-tracker/backend"
  - "apps/aviation-accident-tracker/frontend"
  - "apps/g1000-simulator/backend"
  - "apps/g1000-simulator/frontend"
  - "apps/aviation-chat"
allowBuilds:
  '@apollo/protobufjs': true
  '@scarf/scarf': false
  '@vscode/sqlite3': true
  esbuild: true
  msw: true
  unrs-resolver: true
