services:
  backend-test:
    build:
      context: ../..
      dockerfile: apps/flight-planner/backend/Dockerfile
    command: pytest --ignore=tests/integration_test.py --ignore=tests/test_integration.py
    environment:
      - NODE_ENV=test
      - PYTHONPATH=/app/backend
